### PR TITLE
More corrections on links, better README.md, more donation options on the Sponsor button and some minor changes to the issue templates

### PR DESCRIPTION
**Pull request by MatadorProBr**

### CODE REVIEW

**Comment by OhMyGuus** [comment]
😃

**Comment by JKohlman** [comment]
I really should have noticed those links in the readme on my PR

**Comment by MatadorProBr** [comment]
> I really should have noticed those links in the readme on my PR

Oh lol

**Comment by OhMyGuus** [comment]
Just let me know with a @OhMyGuus or on discord when the PR is finished :)

**Comment by MatadorProBr** [comment]
I think he is ready, I don’t think about anything else I can put, if I have an idea of ​​what I can put on my fork I’ll probably make another pull request here again :)

**Comment by MatadorProBr** [comment]
I think he is ready @OhMyGuus, I don’t think about anything else I can put, if I have an idea of ​​what I can put on my fork I’ll probably make another pull request here again :)

**Pull request merged**
