### PR TITLE
Linux: Re-enable getprocesses, overlay, and keyboard watcher.

### PR DESCRIPTION
**Pull request by TheGreatMcPain**
The overlay does work on Linux, but with some quirks (mainly on tiling window managers).
I still need to add the Linux specific fixes for the overlay, which consist of [disabling hardware acceleration and adding a timeout during window creation.](https://github.com/TheGreatMcPain/CrewLink/commit/09fa0f8dc7d008bfc25a1e3bb181171c54dcfab4).

Luckily the user can fully disable the overlay if they wish via BetterCrewLink's settings. (unlike the original version of CrewLink)

My fork of memoryjs does support getProcesses, so I've re-enabled that code too.

I also have a linux port of [node-keyboard-watcher](https://github.com/TheGreatMcPain/node-keyboard-watcher) which works, but it's not cross-platform friendly yet.

### CODE REVIEW

**Comment by OhMyGuus** [comment]
<3

**Comment by TheGreatMcPain** [comment]
I just added the fixes for getting the overlay to render properly.

**Comment by Donokami** [comment]
> I just added the fixes for getting the overlay to render properly.

Still doesn't work properly, because of electron not applying transparent visuals by default.
But it is easily fixable: In `package.json` script section for electron-webpack, you need to add this option: `--enable-transparent-visuals`.
Howewer, this commandline option for electron should be enabled only for linux platform i imagine

**Comment by TheGreatMcPain** [comment]
> EDIT: the interface also crashes on some clickable elements with this error (doesn't happen on @TheGreatMcPain electron-overlay-window fork, only @OhMyGuus merged one):
> 
> ```
> /home/donokami/x/BetterCrewlink/node_modules/electron/dist/electron --inspect=5858 --enable-transparent-visuals /home/donokami/x/BetterCrewlink/dist/main/main.js: symbol lookup error: /home/donokami/x/BetterCrewlink/node_modules/electron-overlay-window/build/Release/overlay_window.node: undefined symbol: ow_stop
> ```

That's because I haven't updated this pull-request with the most [recent changes to OhMyGuus's fork of `electron-overlay-window`.](https://github.com/OhMyGuus/electron-overlay-window/commit/59a18640bdc5089f1051b03d73822674119f3a18)

**Comment by Donokami** [comment]
> Also when you say, "doesn't work properly", is the overlay not transparent, because it's transparent on my end.

It is fully white on my side, until I enable this --enable-transparent-visuals option. Howewer on my laptop I only have iGPU, no GPU, which could explain this difference

**Comment by TheGreatMcPain** [comment]
Okay, I will try it on my laptop which has an ivybridge intel iGPU.

**Comment by OhMyGuus** [comment]
Finally found time to make the Linux version fully happen +1, I remade the branch since it had a lot of stuff that wasn't needed like you mentioned and moved it to a temp fork so I can test the installation process before it gets fully merged to the main repo. 
Will add u & everyone who made it possible as co-authored when I merge it 👍 

https://github.com/OhMyGuus/BetterCrewlink-Linux

**Pull request closed without merging**
