### PR TITLE
Update/add remote offsets

### PR DESCRIPTION
**Pull request by JKohlman**
Don't merge until we get offset json's figured out!

Todo:

- [x] Fix for x64 support (since broadcast version is the same for x86 and x64)
- [x] Add error for fetch fail
- [ ] Look into updating offsets automatically using github actions (can be done after the merge as well)

### CODE REVIEW

**Comment by OhMyGuus** [comment]
Todo: 

- Fix for x64 support (since broadcast version is the same for x86 and x64)
- Looking into updating it automatic using github actions (can be done after the merge as well)

**Comment by JKohlman** [comment]
Also todo:

- [x] Add error for fetch fail

**Comment by JKohlman** [comment]
A bit of review and testing and it should be good to merge. I think the only necessary changes would be in the offsets repo now.

**Review by OhMyGuus — APPROVED** [review]
:) time to merge

**Pull request merged**
