### PR TITLE
Several changes

### PR DESCRIPTION
**Pull request by MatadorProBr**
ohmyguus

### CODE REVIEW

**Comment by MatadorProBr** [comment]
other conflict aaaaaa

**Comment by MatadorProBr** [comment]
resolved

**Comment by MatadorProBr** [comment]
I wanted to try to make a wiki for the project but I really couldn't because GitHub doesn't like you to make pull requests with wikis, the only way and giving me a collaborator or creating an organization and putting myself in it :/

**Comment by JKohlman** [comment]
How the heck did you manage 47 commits for 13 lines changed lol

**Comment by MatadorProBr** [comment]
> How the heck did you manage 47 commits for 13 lines changed lol

I'm very detailed lol (it's dumb sometimes)

**Comment by OhMyGuus** [comment]
> How the heck did you manage 47 commits for 13 lines changed lol

Good feedback :) squashed it and pushed it again, can't do it with all the commits but yeah

**Pull request merged**
