### PR TITLE
Feature/open all platforms - take two

### PR DESCRIPTION
**Pull request by JKohlman**
Just waiting on Matador to let me know about translations PR then should be good to go

My todo list:

- [x] Test Microsoft Store launcher (Guus)
- [x] Check for bugs resetting settings
- [x] Check if DB migration is needed
- [x] Final cleanup
- [x] Fix translations - Good enough for now
- [x] ~Try to add error checking for URI launches~ Ignoring for now
- [x] FORGOT TO BUMP VERSION NUMBER

This adds a dropdown to the launch screen allowing the "Open Game" button to work on multiple platforms.

### CODE REVIEW

**Comment by JKohlman** [comment]
Working on some visual design changes still before final testing, but shouldn't be too much changing in the backend.

**Comment by JKohlman** [comment]
Alright, I think this should be pretty much good to go. We should go through the translations and update "Microsoft Store" to "Microsoft" but that might be easier with @MatadorProBr's magic. Also any testing/review is appreciated!

**Comment by JKohlman** [comment]
Hey @OhMyGuus I think this should be good to go to merge, we've got a few translations to do yet but those can wait so we can get this in before the update tomorrow

**Comment by OhMyGuus** [comment]
Will merge tomorrow with the update +1 for the work

**Comment by JKohlman** [comment]
Alrighty, just figured you'd want to get this in to help prevent any potential conflicts (there shouldn't really be any but you never know what we need to change)

**Pull request merged**
