### PR TITLE
README.md Update 19/20 June 2021

### PR DESCRIPTION
**Pull request by JasonSmithSO**
_**README.md Update 19/20 June 2021**_

**What's New!**

* Revamped Table Of Contents

* Renamed Section

* Certain Texts Updated

* Certain Sentences Reworded

* Dollar Sign Has Now Moved To The Front Of The Number

_**Future Updates To README.md**_

- More Grammar Updates

### CODE REVIEW

**Comment by OhMyGuus** [comment]
I'm no English expert but why is everything with capital letters? 
Through it was only for titles... and not for the changelog and normal text...

**Comment by JasonSmithSO** [comment]
I did it because I thought it look more professional. I just want a good
look for BetterCrewLink. Sorry if that is an issue. My father is a business
person and his version of this for his business has capital letters in at the beginning
of words.

If you want I can change it back.

Kind Regards

DISABLED WORX (Jason Smith)

**Comment by JasonSmithSO** [comment]
I also reworded some sentences as they didn't sound correct.

**Review by MatadorProBr — COMMENTED** [review]
I don't think anything in Caps would be a good idea, I'll see what I can do, I'll probably leave some stuff in Caps but not everything
(If you want it yourself you can remove it because it's a lot of work, I'm too lazy to do it and I'll probably only do it on Monday)

**Comment by JayisDISABLED** [comment]
That's what I did. I left the Important sentences in Words with Caps

**Comment by disabledworx** [comment]
That's what I did. I left the important sentences with words with caps and the non important without caps

**Comment by JasonSmithSO** [comment]
> I don't think anything in Caps would be a good idea, I'll see what I can do, I'll probably leave some stuff in Caps but not everything
> 
> (If you want it yourself you can remove it because it's a lot of work, I'm too lazy to do it and I'll probably only do it on Monday)

That's what I did. I left the important sentences with words with caps and the non important without caps

**Comment by MatadorProBr** [comment]
> That's what I did. I left the important sentences with words with caps and the non important without caps

I forgot to see it again I had only seen it before (sorry)

**Comment by JasonSmithSO** [comment]
> > That's what I did. I left the important sentences with words with caps and the non important without caps
> 
> 
> 
> I forgot to see it again I had only seen it before (sorry)

No worries

**Review by MatadorProBr — APPROVED** [review]
It looks good, so I think this pull request can be merged

**Pull request merged**
